// Common
export const RESET = "RESET";

// UI
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

// Login
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_AVATAR_SUCCESS = "FETCH_AVATAR_SUCCESS";

// Form mail
export const FETCH_FORM_MAIL = "FETCH_FORM_MAIl";
export const FETCH_FORM_MAIL_SUCCESS = "FETCH_FORM_MAIL_SUCCESS";
export const FETCH_FORM_MAIL_EDIT = "FETCH_FORM_MAIL_EDIT";
export const FETCH_FORM_MAIL_EDIT_SUCCESS = "FETCH_FORM_MAIL_EDIT_SUCCESS";
export const UPDATE_FORM_MAIL_PAGING = "UPDATE_FORM_MAIL_PAGING";
export const DELETE_FORM_MAIL = "DELETE_FORM_MAIL";
export const SAVE_FORM_MAIL = "SAVE_FORM_MAIL";

// Form rate
export const FETCH_FORM_RATE = "FETCH_FORM_RATE";
export const FETCH_FORM_RATE_SUCCESS = "FETCH_FORM_RATE_SUCCESS";
export const FETCH_FORM_RATE_EDIT = "FETCH_FORM_RATE_EDIT";
export const FETCH_FORM_RATE_EDIT_SUCCESS = "FETCH_FORM_RATE_EDIT_SUCCESS";
export const UPDATE_FORM_RATE_PAGING = "UPDATE_FORM_RATE_PAGING";
export const DELETE_FORM_RATE = "DELETE_FORM_RATE";
export const SAVE_FORM_RATE = "SAVE_FORM_RATE";

// Create rate 
export const DELETE_CREATE_RATE = "DELETE_CREATE_RATE";
export const SAVE_CREATE_RATE = "SAVE_CREATE_RATE";

// Rate upload
export const FETCH_LIST_RATE_UPLOAD = "FETCH_LIST_RATE_UPLOAD";
export const FETCH_LIST_RATE_UPLOAD_SUCCESS = "FETCH_LIST_RATE_UPLOAD_SUCCESS";
export const SAVE_RATE_UPLOAD = "SAVE_RATE_UPLOAD";
export const DELETE_RATE_UPLOAD = "DELETE_RATE_UPLOAD";
export const UPDATE_LIST_RATE_UPLOAD_PAGING = "UPDATE_LIST_RATE_UPLOAD_PAGING";

// Handle rate
export const FETCH_FORM_HANDLE_RATE = "FETCH_FORM_HANDLE_RATE";
export const FETCH_FORM_HANDLE_RATE_SUCCESS = "FETCH_FORM_HANDLE_RATE_SUCCESS";
export const FETCH_LIST_HANDLE_RATE = "FETCH_LIST_HANDLE_RATE";
export const FETCH_LIST_HANDLE_RATE_SUCCESS = "FETCH_LIST_HANDLE_RATE_SUCCESS";
export const FETCH_LIST_HANDLE_RATE_SAVE_SUCCESS = "FETCH_LIST_HANDLE_RATE_SAVE_SUCCESS";
export const FETCH_LIST_HANDLE_RATE_COMPLETE_SUCCESS = "FETCH_LIST_HANDLE_RATE_COMPLETE_SUCCESS";
export const FETCH_HANDLE_RATE = "FETCH_HANDLE_RATE";
export const FETCH_HANDLE_RATE_SUCCESS = "FETCH_HANDLE_RATE_SUCCESS";

//Report
export const FETCH_LIST_TOTAL_RATE = "FETCH_LIST_TOTAL_RATE";
export const FETCH_LIST_TOTAL_RATE_SUCCESS = "FETCH_LIST_TOTAL_RATE_SUCCESS";
export const UPDATE_TOTAL_RATE_PAGING_SCO = "UPDATE_TOTAL_RATE_PAGING_SCO";
export const UPDATE_TOTAL_RATE_SEARCH_SCO = "UPDATE_TOTAL_RATE_SEARCH_SCO";
